### ISSUE TITLE
Add MPI implementation detection to build-probe-mpi

### ISSUE THREAD

**Issue by AndrewGaspar** [rsmpi/rsmpi#102]
It should be possible to detect the version of MPI being built against. One of the main reasons to do this is that it allows us to patch around issues in specific MPI implementations.

OpenMPI: Look for `ompi_info` next to `mpicc`
MPICH: Look for `mpichversion` next to `mpicc`
Intel MPI: `impi_info -h`
Spectrum MPI: `ompi_info`, but look for e.g. `Spectrum MPI: 10.3.0.01rtm3`
MS-MPI: Already done.

We'll want to output cfgs that correspond to each of these so they can be used in the rsmpi code for feature detection. `build-probe-mpi` should add some capability to just automatically output all the cfgs so it's easy for downstream crates to get all the same cfgs.

Considerations:
Intel MPI is based off MPICH and Spectrum MPI is based off OpenMPI - should they emit cfg=openmpi and cfg=mpich respectively, in addition to vendor-specific cfgs? I think probably so.

**Comment by jedbrown** [comment]
MSMPI, Cray MPI, and MVAPICH are also based on MPICH. Is the idea here to compensate for implementation quirks or to match ABIs? I've encountered plentiful quirks/bugs in vendored derivatives over the years and sometimes they never get fixed, but most of those can't really be remedied by rsmpi. Some respond to environment variables to modify choice of algorithms. In any case, I feel like reporting the implementation is kind of like a web browser's user agent string (almost unusable). If there are quirks that have to be worked around, I think it's better to detect the quirk.

**Comment by jedbrown** [comment]
I think with our better pkg-config support (plus Cray, etc.), this shouldn't be needed unless we're at the point of supporting experimental features or working around implementation bugs in particular MPI versions. This detection would of course be important if we adopted a different strategy to avoid a bindgen dependency (https://github.com/rsmpi/rsmpi/issues/28), but I don't see us going that way in the near future (it's a much higher maintenance load and arguably the wrong level of abstraction). So I'll close, but feel free to repoen.
