### ISSUE TITLE
Idle when run inside a SLURM job

### ISSUE THREAD

**Issue by mofeing** [rsmpi/rsmpi#105]
I'm testing whether we can use this crate inside a HPC cluster by trying to run the examples.

If I try to run it inside a SLURM job, it outputs nothing and the program freezes when running `mpi::initialize().unwrap()`.
But if I run it on the login node, the programs runs correctly.

I can't imagine what is happening. Any help?

**Comment by bsteinb** [comment]
I assume a simple C/C++/Fortran MPI program works as expected? Are you launching the Rust program differently? Can you run `ldd` on the executable to see if it is linked to the MPI library you expected?

**Comment by mofeing** [comment]
> I assume a simple C/C++/Fortran MPI program works as expected?

Yep, I'm running it on a supercomputer so MPI programs are launched all the time.

> Are you launching the Rust program differently?

I have tried using `cargo mpirun`, `mpirun`, `mpiexec` and `srun` but the result is the same.

> Can you run `ldd` on the executable to see if it is linked to the MPI library you expected?

The executable is correctly linked. Below it is the result of calling `ldd` to the readme example.

```
linux-vdso.so.1 (0x00007ffc55fa1000)
/opt/.snoopy/lib/libsnoopy.so (0x00007f8eb3335000)
libmpi.so.12 => /apps/INTEL/2017.4/impi/2017.3.196/lib64/libmpi.so.12 (0x00007f8eb260d000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f8eb2409000)
librt.so.1 => /lib64/librt.so.1 (0x00007f8eb2201000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8eb1fe4000)
libgcc_s.so.1 => /apps/GCC/7.2.0/lib64/libgcc_s.so.1 (0x00007f8eb1dcd000)
libc.so.6 => /lib64/libc.so.6 (0x00007f8eb1a2c000)
/lib64/ld-linux-x86-64.so.2 (0x00007f8eb37a9000)
```

**Comment by bsteinb** [comment]
> Yep, I'm running it on a supercomputer so MPI programs are launched all the time.

Yes, that is not what I was asking. Let me be more specific. (See, the information you have provided initially does not allow me to do very much. You are trying to run a program, which you have not shared with us, that uses some version, which you have not specified, of `rsmpi`, on some supercomputer. You are using some MPI library, which I now know to be IntelMPI 2017.3.196, and some C compiler, which I now suspect is GCC 7.2.0. And Slurm.) My question was, if you yourself, not someone in general who also uses the system, compiles a C program using exactly that combination of C compiler and MPI library, does it work as expected?

Moreover, I would like to know at least what version of `rsmpi` you are using. Ideally, I would also like to have access to the program you are trying to run. Is it one of the examples distributed with `rsmpi`?

**Comment by mofeing** [comment]
Ouch yes. My bad. I forgot to give this basic info. Sorry, it was last hour at work and my mind wasn't functioning as good.
- Intel MPI 2017.4
- rsmpi @ `master` branch
- GCC 7.2.0
- rustc 1.49.0 (e1884a8e3 2020-12-29)
- LLVM 10.0.1

Well, all I'm trying right now is to run the examples of this crate; specifically the `readme` example but any other will suffer from the same. I've cloned the repo so I'm using the master branch.

> My question was, if you yourself, not someone in general who also uses the system, compiles a C program using exactly that combination of C compiler and MPI library, does it work as expected?

Yes. In order to be sure, I've run [this code](https://www.mcs.anl.gov/research/projects/mpi/mpi_ruby/talks/mcs/example3-1.html) and it worked perfectly.

**Comment by mofeing** [comment]
I've tried with OpenMPI 4.0.1 (and GCC 8.1.0) and it worked!

So I guess that `rsmpi` does not work with Intel MPI?

**Comment by jedbrown** [comment]
We have CI for Open MPI 4.1 now and I'm going to assume from the above that this is working now. Feel free to reopen if you still have reproducible failures on `main`.

**Comment by huapengcheng** [comment]
I have used cargo-mpirun to run a small demo on only one node.It was successful.But I don't know how to run it on my cluster which has been used successfully with mpich3 on language C.

**Comment by jedbrown** [comment]
`cargo-mpirun` is hard-coded to call the `mpiexec` executable. On a cluster, you'll usually need to use a command like `srun` (Slurm) instead. Those generally have different command-line options so it would take some effort to make a `cargo-srun`. You can build the binary and invoke it directly, as in `srun [options] target/debug/examples/immediate_barrier`.

**Comment by huapengcheng** [comment]
Thanks for your useful reply.Yesterday I tried to install "srun" and faced some problems.
One of them likes following: 


I used the command "cargo install srun" and the found the problem above.I have use RUST for just a few days.I can not find useful ways to overcome it.Please help me.I am looking forward to your reply soon.Thanks again!!!
| |
花鹏程
|
|
***@***.***
|
On 9/19/2022 23:02，Jed ***@***.***> wrote：

cargo-mpirun is hard-coded to call the mpiexec executable. On a cluster, you'll usually need to use a command like srun (Slurm) instead. Those generally have different command-line options so it would take some effort to make a cargo-srun. You can build the binary and invoke it directly, as in srun [options] target/debug/examples/immediate_barrier.

**Comment by jedbrown** [comment]
You'll have to read the docs for your cluster. `srun` is part of SLURM, which is a common resource manager for HPC systems. There are several others. Your cluster should have documentation, and you can ask the cluster admins if not. These tools have nothing to do with Rust, but the Rust executables can be run like any other.

**Comment by huapengcheng** [comment]
Thanks for your reply.Today I have installed the "slurm" with two nodes.


I can use the command "srun -h" and it works.But I can't still install srun in my Rust project.Its result does not change.


And I don't know how to use "srun" correctly.My test is following:


It can't run correctly.I am looking forword to your reply.
Thanks again.


| |
花鹏程
|
|
***@***.***
|
On 9/20/2022 12:20，Jed ***@***.***> wrote：

You'll have to read the docs for your cluster. srun is part of SLURM, which is a common resource manager for HPC systems. There are several others. Your cluster should have documentation, and you can ask the cluster admins if not. These tools have nothing to do with Rust, but the Rust executables can be run like any other.

**Comment by jedbrown** [comment]
I'm sorry, but this is out of scope for the rsmpi issue tracker. You don't "install srun in [a] project", you use it to run jobs on the cluster.

**Comment by huapengcheng** [comment]
Thanks.I have successfully run the demo on my cluster.I just did not use the command "srun" correctly.


I am glad that I have overcomed this problem.This makes me learn a lot!
Thank you very much!
Wishing you the best of health and success!


| |
花鹏程
|
|
***@***.***
|
On 9/20/2022 20:44，Jed ***@***.***> wrote：

I'm sorry, but this is out of scope for the rsmpi issue tracker. You don't "install srun in [a] project", you use it to run jobs on the cluster.
