### ISSUE TITLE
Some traits are not object safe, but could be.

### ISSUE THREAD

**Issue by ZackJorquera** [rsmpi/rsmpi#108]
Hi,

I just started using this library, so I'm not very familiar yet, but I encountered a problem. I realized that the `Communicator` trait is not currently "object safe," so something like the following will fail to compile.

```rust
fn foo(comm: &dyn Communicator) { }
```

This is something I need for my application as I don't want to care what specific type of communicator I have, and I only need a small subset of the methods like `size()`, `rank()`, and `as_raw()`.

It seems to be a fairly easy fix as all that is needed is to add the trait bound `Self: Sized` to the methods that use generics. 

I haven't looked around much, but I also found that the same thing applies to the `Group` trait.

Is this a change you would want?

**Comment by jedbrown** [comment]
@ZackJorquera Would you be up for making a PR with this?
