### ISSUE TITLE
is mpi::initialize_with_threading(Threading::Multiple) thread safe in rsmpi

### ISSUE THREAD

**Issue by jianshu93** [rsmpi/rsmpi#115]
Hello team,
Standard MPI like OpenMPI and MAVPICH, the threading support, especially multiple requires thread safety code. I am wondering whether this wrapper will inherit rust thread safety feature and it is just an unsafe bindings to MPIs. I did not see some descriptions or discussions.

Thanks,

Jianshu

**Comment by jedbrown** [comment]
The threading mode allows calling MPI (the C interface) from multiple threads.
> Multiple threads may call MPI, with no restrictions.

I'm not aware of new threading/safety problems at the Rust/C interface, but please file an issue if you find something.

**Comment by bsteinb** [comment]
There is this related issue: https://github.com/rsmpi/rsmpi/issues/12

In Rust, whether an API is thread safe or not is a compile time property expressed by the API's types implementing `Send` or `Sync`. For MPI, thread safety is a dynamic property, determined at run time. `rsmpi` currently fails to translate the thread safety guarantees and constraints described in the MPI standard into Rust compile time equivalents. As a consequence, the Rust compiler will not stop you from using MPICH from multiple threads even when MPI has been initialized with `MPI_THREAD_SINGLE` (this is unsafe). The opposite is true for `rsmpi` built on top of `OpenMPI` where the rust compiler will not let you use it from multiple threads even if MPI has been initialized with `MPI_THREAD_MULTIPLE` (this is overly restrictive).

**Comment by jedbrown** [comment]
Thanks @bsteinb.

I think the question is asking whether it's safe to use threads when using `MPI_THREAD_MULTIPLE`, and I think the answer is yes (modulo not actually being able to do it with Open MPI because of bindgen leaks). Making the usability (and safety with Single/Funneled) better is another task. I'll close this issue, but feel free to reopen.
