### ISSUE TITLE
non-blocking communication

### ISSUE THREAD

**Issue by jianshu93** [rsmpi/rsmpi#117]
Hello team,

Is there a place where I can see the entire function defined/used, compare to OpenMPI, et.al., for example, I do not see nonblocking isend and irecv in examples, or I missed it?

Thanks,

Jianshu

**Comment by jedbrown** [comment]
Did you check out this example?
https://github.com/rsmpi/rsmpi/blob/main/examples/immediate.rs

This ends up using `MPI_ANY_TAG`, which can harm performance and interfere with different phases so applications usually manage tags themselves. Would it help to have an example of neighbor exchange, say for a ring of processors?

**Comment by jianshu93** [comment]
Oh Thanks,

I thought immediate should be something related to isend/irecv but not sure. There are also a log of like MPI_test, MPI_waitany/some/all et.al. Just want to be sure each implementation is available.

Thanks,

Jianshu
