### ISSUE TITLE
Example project of integrating rsmpi into mpi4py with maturin

### ISSUE THREAD

**Issue by tbetcke** [rsmpi/rsmpi#118]
Hi,

I have created a small demonstration project of how to pass a communicator from mpi4py into rsmpi using automatically generated cffi bindings from `maturin`. 

The code is available at:

https://github.com/betckegroup/mpi4py_with_rsmpi

The difficulty was passing the communicator. If we directly want to pass a pointer to MPI_Comm we would have to include the "mpi.h" header file into the maturin build process, which caused us quite a few errors. So we ended up converting a pointer to MPI_Comm into a uintptr_t and passed this to a Rust usize, from where we could convert this back to a pointer to MPI_Comm. Since maturin only sees a C interface that takes an integer this is straightforward to generate bindings for and is handled automatically by maturin.

If you think it useful I would be happy for a link to this demonstration project to be added to the rsmpi documentation.

**Comment by jedbrown** [comment]
Thanks for building this example. I think we could add a section to the README (or other place in the docs) with recommended demonstrations. That could be further split into simple demos and featured production apps/libraries. In this case, I'd almost say we can include it in the rsmpi repo directly, but that might require some labor to ensure it's tested in CI. Feel free to make a PR either way (just docs or making it a demo that's tested on at least one platform).

**Comment by jedbrown** [comment]
Resolved by #129.
