### ISSUE TITLE
Can't get example code to build.

### ISSUE THREAD

**Issue by sbromberger** [rsmpi/rsmpi#119]
I'm using
```
gcc -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi
```
on `Linux hydrogen 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`.

with rsmpi v0.5.4.

`cargo build` on the example code yields the following: https://gist.github.com/sbromberger/b3d7897ae8fa331729f945cb73c6bbb2

bottom line error:
```
thread 'main' panicked at 'Unable to find libclang: "couldn't find any of ['libclang.so', 'libclang.so.*', 'libclang-*.so']
, set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', /home/seth/.loc
al/share/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.31.3/src/lib.rs:1518:31
```

But even setting `LIBCLANG_PATH=/usr/lib/x86_64-linux-gnu/openmpi/lib` doesn't seem to help.

What am I doing wrong here?

**Comment by jedbrown** [comment]
It's searching for libclang, not your MPI. Do you have libclang installed?

**Comment by sbromberger** [comment]
ugh. sorry. That plus `mpi = { git = "https://github.com/bsteinb/rsmpi", rev = "f9aec8b8d82" }` did the trick. Thanks.
