### ISSUE TITLE
Error running example in docs

### ISSUE THREAD

**Issue by dstansby** [rsmpi/rsmpi#135]
I've just tried copy/pasting and running the [first example in the docs](https://docs.rs/mpi/latest/mpi/#usage), and I get the error:

```rust
thread 'main' panicked at 'Size of MPI_COMM_WORLD must be 2, but is 1!', src/main.rs:12:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c97d02cdb5ca5f5e9eff1fa9e4560d220d1fd2a0/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/c97d02cdb5ca5f5e9eff1fa9e4560d220d1fd2a0/library/core/src/panicking.rs:142:14
   2: sparse_matrix::main
             at ./src/main.rs:12:9
   3: core::ops::function::FnOnce::call_once
             at /rustc/c97d02cdb5ca5f5e9eff1fa9e4560d220d1fd2a0/library/core/src/ops/function.
```

I'm guessing this is because I need to set `MPI_COMM_WORLD` to 2 somewhere, but it's not obvious from the error message or example in the documentation how I can do this.

I think a good way to fix this would be to add a link or short explanation next to the examples in the docs explaining how to set `MPI_COMM_WORLD=2`

**Comment by jedbrown** [comment]
This comes from the launch environment. Here's what you probably tried (roughly)
```console
$ cargo run --example demo
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/examples/demo`
thread 'main' panicked at 'Size of MPI_COMM_WORLD must be 2, but is 1!', examples/demo.rs:12:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
You can run the executable directly like this
```console
$ mpiexec -n 2 target/debug/examples/demo
Process 1 got message [4.0, 8.0, 15.0].
Status is: Status { source_rank: 0, tag: 0 }
```
You can also use the [cargo-mpirun](https://crates.io/crates/cargo-mpirun) package for better ergonomics.

How do you reckon would be a good way to document this in the docs you read?

**Comment by jedbrown** [comment]
I'll close this assuming that it worked for you, but feel free to reopen.
