### ISSUE TITLE
How to define my own structs from someone in my program for communication of MPI?

### ISSUE THREAD

**Issue by huapengcheng** [rsmpi/rsmpi#136]
I want to send and receive a complex struct which used in “elliptic curve”.It is in "https://docs.rs/group/0.12.1/group/trait.Curve.html" which means one point on a “elliptic curve”.I want to know how to use the existed struct "Curve" to create a "UserDatatype" for MPI communication.I want something different from the rsmpi/examples.

**Comment by jedbrown** [comment]
Are you saying you don't have a struct, but want to create a derived datatype? Note the [struct.rs example](https://github.com/rsmpi/rsmpi/blob/main/examples/struct.rs#L28-L33), which contains things like:
```rs
    #[derive(Equivalence)]
    struct MyProgramOpts {
        name: [u8; 100],
        num_cycles: u32,
        material_properties: [f64; 20],
    }
```
You can also manually derive `Equivalence`, perhaps using `cargo-expand` to see examples of how the derive macro works.

**Comment by huapengcheng** [comment]
Actually,I want to send something which is a "group::prime::PrimeCurveAffine::Curve" between different processes.It consists of 3 "Fp"s and every "Fp" consists of 6 "u64"s when it is "G1Project".I'm not familiar with "Rust".I am finding ways to finish the communication.Can you help me?The "group::prime::PrimeCurveAffine::Curve" is in"https://docs.rs/group/0.12.1/group/prime/trait.PrimeCurveAffine.html".Can I transmit it directly with "p2p"?

**Comment by jedbrown** [comment]
You're linking to a trait, but you don't send a trait. You can send a struct that implements the trait, though those docs don't include implementors. (Perhaps because they live in a different crate? I can be more explicit if you link to the struct that implements `PrimeCurveAffine`.)

**Comment by huapengcheng** [comment]
Sorry!I can not find some structs that implement  "PrimeCurveAffine".I think it may use the trait to be a parameter.
It is used to create a variable.
![image](https://user-images.githubusercontent.com/88694422/197449287-e8a26363-dbe2-4b0a-852b-b12c23101278.png)
![image](https://user-images.githubusercontent.com/88694422/197449335-bab33061-f189-4456-91f4-e39fbb20502e.png)

**Comment by huapengcheng** [comment]
![image](https://user-images.githubusercontent.com/88694422/197475993-0970b866-3e5c-41f7-9c1e-96005149a3ac.png)
II find "G1Affine" implement PrimeCurveAffine.And "G2Affine" implements ,too.I think such makes both G1 and G2 work with the same codes.I just want to modify G1 now,but I have no way.I want to know how to make it be G1.

**Comment by jedbrown** [comment]
Please link to the definition of `G1Affine`.

**Comment by huapengcheng** [comment]
Sorry for bothering you again!
I am thinking of other ways to finish my problem.I find that G1Affine implements "PrimeCurveAffine".And I create a variable like following:
![image](https://user-images.githubusercontent.com/88694422/197684504-0729e9b2-99fa-4274-84ee-974775c374f1.png)
I want to know how to use functions in the the definition of G1Affine.
![image](https://user-images.githubusercontent.com/88694422/197684758-e54a8b3b-e55d-495c-aab4-cba53991b78c.png)
I want to use something like below:
![image](https://user-images.githubusercontent.com/88694422/197684868-ce66d4a9-80d0-48a4-ad08-7ea56868589d.png)
Can such work?

**Comment by huapengcheng** [comment]
Thank you for your reply.I still can not understand "link to G1Affine/G1Projective".What does this mean?

**Comment by jedbrown** [comment]
You're sharing screenshots that don't show the code. If the code is open, it would be much more useful to link to the code. I see it's part of the `blst` package, and that `G1Affine` is a newtype of [`blst_p1_affine`](https://docs.rs/blst/0.3.10/blst/struct.blst_p1_affine.html), which contains `u64` arrays. You can send this type directly with rsmpi.

**Comment by huapengcheng** [comment]
The codes that I am studing are from "https://github.com/filecoin-project/ec-gpu/blob/master/ec-gpu-gen/src/multiexp.rs#L317".I want to transmit the "acc" which is a [<G as PrimeCurveAffine>::Curve] between different processes.

**Comment by jedbrown** [comment]
I'm sorry, but I don't have capacity to carry on this conversation at this time. You're looking at an associated type. If you have a G1Affine, then [this says](https://docs.rs/blstrs/latest/src/blstrs/g1.rs.html#729) that associated type is [`G1Projective`](https://docs.rs/blstrs/latest/blstrs/struct.G1Projective.html), which is a newtype'd [`blst_p1`](https://docs.rs/blst/0.3.10/blst/struct.blst_p1.html), which again, is a simple struct with array members, and thus can be sent by rsmpi. Please read and adapt the examples. I can't write your code for you.
