### ISSUE TITLE
Add `#[inline(always)]` mark for common functions

### ISSUE THREAD

**Issue by Evian-Zhang** [rsmpi/rsmpi#137]
Before my question, I want to express my appreciation for this library's maintainers that thank you for enriching Rust with MPI ecosystem.

I have used `mpi`, `mpi-sys` and direct C to write some simple MPI logic, and found that `mpi` is slower than `mpi-sys` (2x-3x) (not comprehensive benchmarking, just some experiments), and `mpi-sys`'s performance is near C. For Rust projects,  I compile such codes in Rust's release profile (`cargo build --release`), and C is `mpicc` with `O3`.

After digging into binary code, I found two interesting part:

* Constant Loading

  In C, constants such as `MPI_ANY_TAG` are directly moved to registers, while in Rust, they are accessed via memory reading. This is due to our library treats such constants as static, and I find out an old issue ([rsmpi/rsmpi#62](https://github.com/rsmpi/rsmpi/issues/62)) regarding this, so my issue will not focus on this.
* Function Inlining

  It is very strange that:

  * Every access to common communicator (i.e. we use `world.some_function()` in user code, and the library will get common communicator from the `world`) is compiled to a function call rather than just loading `MPI_COMM_WORLD`. I add `#[inline(always)]` in `src/topology/mod.rs`'s  `world()` and `from_raw_unchecked()` methods for `SystemCommunicator`, and `as_raw()` in `SystemCommuniactor`'s implementation for `AsRaw`. And this problem solved.
  * There are many  `from_raw` + `as_raw` pair in the code (such as when calling `equivalent_datatype`), which I think could be optimized by Rust compiler (just load the raw to register) but it is not. And function inlining doesn't seem to solve this.

  In my understanding, both of above two things SHOULD be optimized by Rust compiler without any manual adjustment, and I can't dig deeper into the Rust logic why this can't be optimized (maybe is because `unsafe`? And more strange, all such functions are called indirectly). This two things may be the main reason for wrapper slower than binding, and maybe adding some inlining could solve this problem.

**Comment by jedbrown** [comment]
Can you describe the experiments/benchmarks you're using for this comparison?

**Comment by Evian-Zhang** [comment]
@jedbrown Thank you for reply. 

My codes are in [Evian-Zhang/parallel-bench](https://github.com/Evian-Zhang/parallel-bench). The readme is written in Chinese, but it doesn't matter, the core figures inside it are in English.

In short, my experiments is just to add a large array in parallel and output the result. A node will divide the array it receives into two part, one part sending to next node, the other will continue the division until no nodes remain. Then each node collects the result and send to the parent.

**Comment by Evian-Zhang** [comment]
[Using LLVM's lto](https://doc.rust-lang.org/cargo/reference/profiles.html#custom-profiles) solves all the problems. 

# How about changing the default settings for rsmpi's release profile?

Let's take [`receive_vec`](https://rsmpi.github.io/rsmpi/mpi/point_to_point/trait.Source.html#method.receive_vec) for example. If our code uses this API to receive into a vector of `usize`, when compiling it using the default release profile settings via `cargo build --release`, the generated binary will contains a call for `usize::equivalent_datatype`:

```asm
call  cs:_ZN52_$LT$usize$u20$as$u20$mpi__datatype__Equivalence$GT$19equivalent_datatype17h282b4dfa1a754dd8E_ptr
```

where `_ZN52_$LT$usize$u20$as$u20$mpi__datatype__Equivalence$GT$19equivalent_datatype17h282b4dfa1a754dd8E_ptr` is a static variable in `.got` section, which points to `_ZN52_$LT$usize$u20$as$u20$mpi__datatype__Equivalence$GT$19equivalent_datatype17h282b4dfa1a754dd8E`, which moves the static `RSMPI_UINT64_T` into the corresponding registers.

The reason for this indirect call (i.e. find the true callee address via accessing a pointer in memory) is that, when generating LLVM IR code, Rust compiler leaves the call site in the module of user code, and inside rsmpi's llvm module, it collects all the functions which have the same code (such as `UncommittedUserDatatype::as_raw` and `UserDatatype::as_raw`), and creates [alias](https://releases.llvm.org/14.0.0/docs/LangRef.html#aliases) to reduce code size. This indirection of two separate LLVM modules makes LLVM optimizer unable to inline and further optimize the behaviors. I'm currently not show the core reason of this incapability, and whether not using aliases in LLVM could solve this problem. However, using lto, LLVM can optimize between modules, and we can get the desired optimizations.

**Comment by Evian-Zhang** [comment]
After checking my code one more time, I found something silly. I wrongly extend the input before communication, leading the sending buffer 8x larger.

Fixing the bug and turning on lto, it seems that rsmpi is even faster than C code!!! I am doing a full bench and will update the result later.

So the indirection call and poor optimization mentioned above does not affect the running time much. However, turning on lto or inling always does make the performance better. Hope the author of this crate could investigate it more to make it the best mpi library ever.

**Comment by Evian-Zhang** [comment]
@jedbrown 

After conducting a full bench, yes, the communication latency is the core part, and inlining optimization does improve the performance a little bit. For the above-mentioned experiment, with input size of 2^29 and 16 kernels, the run time difference is 5575 microseconds (227155.2 for inlining optimized, 232730.2 for not).

And yes, the performance improvement does not meet with the longer compiling time for enabling lto. So I don't think enable lto for common usage of this crate is worthwhile. 

Anyway, I am also very excited that using rsmpi is faster than native C in every benchmark set (input_size & kernel_count) of my experiment (raw experiment result has been uploaded to my above-mentioned GitHub repo). Thank you for your excellent work to bring mpi to rust.

**Comment by jedbrown** [comment]
Thanks. I'm skeptical even of this result (versus other system noise/thermal throttling or other configuration disparity) because lack of inlining is nanoseconds and you aren't moving through that calling interface millions of times. Also for the other comparisons, I think a more careful profile will show that it's all the same unless your benchmark configuration creates an extra copy or buffer traversal.
