### ISSUE TITLE
`barrier()` not synchronizing correctly

### ISSUE THREAD

**Issue by Noxdor** [rsmpi/rsmpi#138]
Just getting started with your crate and I am loving it so far, specially comparing it to my Profs examples in C on the slides.

I was trying an example with `broadcast_into()` and wanted to synchronize the processes' stdout outputs to see the buffers before and after broadcast. Unfortunately I can't make it work and I am starting to get the feeling, something is wrong with the synchronisation of `barrier()`. It could be as something I am overseeing here due to lack of experience with `mpi`. Could someone please tell me if they can reproduce this problem or if the error is due to my code?

```rust
use mpi::traits::*;

fn main() {
    let universe = mpi::initialize().unwrap();

    let world = universe.world();
    let rank = world.rank();

    // send-receive buffer
    let mut msg = [0; 256];

    if rank == 0 {
        let msg_str = "\"This is a broadcast!\"".as_bytes();
        for i in 0..msg_str.len() {
            msg[i] = msg_str[i];
        }
        println!("Before broadcast: ");
    }

    world.barrier();

    println!(
        "Process @ rank {} has buffer: {}",
        rank,
        std::str::from_utf8(&msg).unwrap()
    );

    world.barrier();

    // first process broadcasts to all others
    world.process_at_rank(0).broadcast_into(&mut msg);

    if rank == 0 {
        println!("\nAfter broadcast:");
    }

    world.barrier();

    println!(
        "Process @ rank {} has buffer: {}",
        rank,
        std::str::from_utf8(&msg).unwrap()
    );
}
```

I expect to see only one process (0) to have "This is a broadcast!" in it's buffer before broadcasting and all of the after it. Sometimes that is actually the result I get. Sometimes it is something like the result below, where process at rank 1 prints the first message too late. This should not be possible, since at this point in time he already received data via broadcast, right?

```md
Before broadcast: 
Process @ rank 2 has buffer: 
Process @ rank 3 has buffer: 
Process @ rank 4 has buffer: 
Process @ rank 5 has buffer: 
Process @ rank 0 has buffer: "This is a broadcast!"

After broadcast:
Process @ rank 0 has buffer: "This is a broadcast!"
Process @ rank 1 has buffer: 
Process @ rank 1 has buffer: "This is a broadcast!"
Process @ rank 5 has buffer: "This is a broadcast!"
Process @ rank 2 has buffer: "This is a broadcast!"
Process @ rank 3 has buffer: "This is a broadcast!"
Process @ rank 4 has buffer: "This is a broadcast!"
```

**Comment by AndrewGaspar** [comment]
This is probably down to stdio buffering.

Try running this before each barrier:
```
std::io::stdout().flush()
```

**Comment by Noxdor** [comment]
> This is probably down to stdio buffering.
> 
> Try running this before each barrier:
> 
> ```
> std::io::stdout().flush()
> ```

Thank you for your reply! I actually thought the same and already tried it with flushing the stdio buffer, but unfortunately that doesn't seem to be the cause of the problem. I adjusted the code to
```rust
use mpi::traits::*;
use std::io::Write;

fn main() {
    let universe = mpi::initialize().unwrap();

    let world = universe.world();
    let rank = world.rank();

    // send-receive buffer
    let mut msg = [0; 256];

    if rank == 0 {
        let msg_str = "\"This is a broadcast!\"".as_bytes();
        for i in 0..msg_str.len() {
            msg[i] = msg_str[i];
        }
        println!("Before broadcast: ");
    }

    std::io::stdout().flush().unwrap();
    world.barrier();

    println!(
        "Process @ rank {} has buffer: {}",
        rank,
        std::str::from_utf8(&msg).unwrap()
    );

    std::io::stdout().flush().unwrap();
    world.barrier();

    // first process broadcasts to all others
    std::io::stdout().flush().unwrap();
    world.process_at_rank(0).broadcast_into(&mut msg);

    if rank == 0 {
        println!("\nAfter broadcast:");
    }

    std::io::stdout().flush().unwrap();
    world.barrier();

    println!(
        "Process @ rank {} has buffer: {}",
        rank,
        std::str::from_utf8(&msg).unwrap()
    );
}
```

And still get results like
```md
Before broadcast: 
Process @ rank 4 has buffer: 
Process @ rank 5 has buffer: 
Process @ rank 0 has buffer: "This is a broadcast!"

After broadcast:
Process @ rank 2 has buffer: 
Process @ rank 3 has buffer: 
Process @ rank 5 has buffer: "This is a broadcast!"
Process @ rank 4 has buffer: "This is a broadcast!"
Process @ rank 3 has buffer: "This is a broadcast!"
Process @ rank 1 has buffer: 
Process @ rank 1 has buffer: "This is a broadcast!"
Process @ rank 0 has buffer: "This is a broadcast!"
Process @ rank 2 has buffer: "This is a broadcast!"
```
Just do give further information that might help, I am using `just` as a command runner to run the following two steps for compiling and running this example locally on my machine:

```make
default: (run "6")

run count: build
  mpiexec -n {{count}} target/release/mpi_collective_operations
  

build:
  cargo build --release
```

This builds the example as a release version and runs it with `mpiexec`. It also can't be a problem with a compiler optimization because running it with the build version, it causes the same issues. As far as I understand, my installed mpi implementation is ompi, that is the only version that gave me a result checking for it using `pkg-config`.

**Comment by Noxdor** [comment]
@AndrewGaspar could you find the time to copy my code and try to reproduce this problem on your machine?

**Comment by Noxdor** [comment]
> I don't think this is an rsmpi issue. This depends a lot on the environment and the specific mpi implementation.
> 
> If you need output with a guaranteed order, I'd suggest only printing on one rank.

Thank you for your input! I am far from understanding the little things happening in the background and the differences between mpi implementations, so I'm sure you're right. This was anyway just an experiment, but I was curious about if this was my mistake or from what this unexpected behaviour arose. Anyway, since this issue is most likely not caused by the rsmpi api, I will resolve this issue.
