### ISSUE TITLE
macOS compiling error

### ISSUE THREAD

**Issue by dcompiler** [rsmpi/rsmpi#139]
I have just installed Rust and downloaded rsmpi, using on Mac OS 12.5:

cargo build failed with the following error:

  libtool: install: /usr/bin/install -c .libs/libffi.lai /Users/cding/Library/Mobile Documents/com~apple~CloudDocs/DingDocs/258spring23/projs/rsmpi/target/debug/build/libffi-sys-153b2793a0d033bd/out/libffi-root/lib/libffi.la

  --- stderr
  rm: conftest.dSYM: is a directory
  configure: WARNING: Libtool does not cope well with whitespace in `pwd`
  rm: conftest.dSYM: is a directory
  rm: conftest.dSYM: is a directory
  rm: conftest.dSYM: is a directory
  ../configure: line 18762: -WS: command not found
  clang: error: unsupported option '-print-multi-os-directory'
  clang: error: no input files

**Comment by jedbrown** [comment]
I don't know why this is. We have a [CI test](https://github.com/rsmpi/rsmpi/blob/main/.github/workflows/test.yaml#L33) on MacOS. I wonder if you can identify what is different between that environment and yours.

**Comment by dcompiler** [comment]
Thanks for the reply.  I figured out the problem---I had a space in the rsmpi directory path.  It now installs fine.
