### ISSUE TITLE
Implement Equivalence trait for complex types

### ISSUE THREAD

**Issue by tbetcke** [rsmpi/rsmpi#149]
Hi,

the ```Equivalence``` trait is currently not implemented for complex types (see types in ```datatype.rs```).
It would be simple to add  corresponding definitions for the types ```c32``` and ```c64``` defined in the ```Cauchy``` crate.
This might make sense as this is a widely used package for complex types. However, it would introduce a dependency to ```Cauchy```. Is this possible or not a preferable option for ```rsmpi```? If possible, I will be happy to write a pull request for it.

**Comment by jedbrown** [comment]
It adds a dependency on serde and has a small hit to build time (though only 0.3 seconds in my `cargo clean && cargo build` test of rsmpi, which isn't really a from-scratch). The hedge would be to place it behind a feature flag, but perhaps make it a default feature.

**Comment by jedbrown** [comment]
Let's use a feature flag. Anyone who needs it will be depending on `mpi` already so they have a place to require the feature.
