### ISSUE TITLE
Why I can not compile “mpi-sys”？

### ISSUE THREAD

**Issue by huapengcheng** [rsmpi/rsmpi#153]
I want to use mpi in my project.But when compiling "mpi-sys",it failed like following:
![image](https://user-images.githubusercontent.com/88694422/222621642-d5838cd2-8039-4852-b860-c34ee3d76d5a.png)
How can i do to overcome such problem?

**Comment by jedbrown** [comment]
You need libclang to be installed on your system. You can get it through your package manager.

**Comment by jedbrown** [comment]
I'll assume this is resolved. Feel free to ask if you've installed `libclang` and are still having this issue.
