### ISSUE TITLE
Unstable with openmpi in Arch Linux, yet stable with MPICH from conda

### ISSUE THREAD

**Issue by jreniel** [rsmpi/rsmpi#158]
Dear Devs,
First of all, thank you for the efforts that you are putting on this library, I hope that it continues to grow!

I just wanted to let you know of my experience using this crate. While using Arch Linux with the package:

extra/openmpi 4.1.5-1 (2.9 MiB 9.0 MiB) (Installed)
    High performance message passing library (MPI)
    
it just loves to deadlock for no reason! For example, just by calling world.barrier(), nothing ever goes beyond that. After many hours in frustration trying to find what's wrong with my code, I decided to give a try to a different implementation. To make my life easy, I just installed mpich and mpich-mpicc from conda and lo and behold, the code started working like magic!

I just thought I'd share, feel free to close this if you don't find it useful, but maybe someone else going through the same problems can benefit from the knowledge.

Once again, thanks a lot for your hard work on this crate!

**Comment by jedbrown** [comment]
Are you able to run other MPI programs with your `openmpi`? I've been running that version since Feb with no issues so I suspect misconfiguration in your environment.

**Comment by jreniel** [comment]
@jedbrown 
Thanks for your reply!
So far I haven't had any issue running Fortran code compiled using community/openmpi, but I am open to the possibility of something being amiss on my side.
Do you have any pointers to things I should look at?
I recently did a fresh Arch install on this machine, and I haven't messed around with anything on the system side (at least nothing that may be related to openmpi). 
It's good to know that you have been able to use this configuration because not being able to use openmpi was a bit off-putting for me, but I believe there is hope. Maybe I should try on a different hardware, I have other machines I could try it on...

**Comment by hppritcha** [comment]
an easy way to double check your OpenMPI package (assuming you have downloaded one of the Open MPI tarballs) is to 
- make sure the mpicc in your PATH is pointing to the bin folder of the Open MPI install location
- cd into the examples folders of the open mpi source tree
- make  clean && make 
- do mpirun -np (some number of processes less than or equal to number of cpus on your system) ./hello_c
- same for ring_c

If these work then that's at least a basic sanity check.  there's allso a connectivity_c test which does more messaging in that folder.

**Comment by jedbrown** [comment]
I'll close this issue. Feel free to reopen if you have further information to indicate it's an rsmpi issue.
