### ISSUE TITLE
clippy lint for derived `Equivalence` of struct with tuple fields

### ISSUE THREAD

**Issue by Tehforsch** [rsmpi/rsmpi#162]
Thanks for the great library!

Minimal example:

```rust
use mpi::traits::Equivalence;

#[derive(Equivalence)]
pub struct Foo {
    bar: (i32, i32),
}
```

Running clippy on this yields the following lint twice:
```
warning: this pattern is unneeded as the `..` pattern can match that element
 --> src/main.rs:3:10
  |
3 | #[derive(Equivalence)]
  |          ^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unneeded_wildcard_pattern
  = note: `#[warn(clippy::unneeded_wildcard_pattern)]` on by default
  = note: this warning originates in the macro `_memoffset__field_check_tuple` which comes from the expansion of the derive macro `Equivalence` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This is caused by a macro in the `memoffset` crate. The problem was fixed in this PR:
https://github.com/Gilnaa/memoffset/pull/64

Looking at the changelogs, I suppose that any memoffset version > 0.7.0 should have this fix in it.

Feel free to close if bumping the `memoffset` version is difficult for some unrelated reason, since this is not a big deal at all and one can always `#[allow(clippy::unneeded_wildcard_pattern)]`

**Comment by jedbrown** [comment]
We have a newer memoffset version and I'm about to release 0.7. Is this issue complete?

**Comment by Tehforsch** [comment]
> We have a newer memoffset version and I'm about to release 0.7. Is this issue complete?

Works for me when I build with `jed/release-0.7`. Thanks!
