### ISSUE TITLE
Example of using rsmpi across two or more nodes

### ISSUE THREAD

**Issue by b0xtch** [rsmpi/rsmpi#166]
Does rsmpi support inter node communication or the readme is accurate if not is there an example? 🙏

**Comment by jedbrown** [comment]
Any example works across multiple nodes so long as your MPI is configured appropriately (e.g., a hostfile or resource manager). Note that `cargo mpirun` just uses a plain `mpiexec` internally so if you need to use a different command (e.g., `srun`) then you should build your executables and `srun target/release/your-app`.

**Comment by b0xtch** [comment]
> Any example works across multiple nodes so long as your MPI is configured appropriately (e.g., a hostfile or resource manager). Note that `cargo mpirun` just uses a plain `mpiexec` internally so if you need to use a different command (e.g., `srun`) then you should build your executables and `srun target/release/your-app`.

Thanks @jedbrown
