### ISSUE TITLE
push a release with updated bindgen?

### ISSUE THREAD

**Issue by tbonethuggin** [rsmpi/rsmpi#169]
Hi all,

The current version of mpi-sys v0.2.0 on crates.io has bindgen v0.60 set as a dependency.
Whereas latest master has bindgen v0.65.

Would it be possible to push a new release of mpi-sys to crates.io to pickup this change?
The bindgen update fixes an issue with Clang versions above v14
(see here for reference https://stackoverflow.com/questions/76443280/rust-bindgen-causes-a-is-not-a-valid-ident-error-on-build)

Thanks!

**Comment by jedbrown** [comment]
Thanks, this is coming in #168.
