### ISSUE TITLE
Create `rustfmt.toml`

### ISSUE THREAD

**Issue by Pencilcaseman** [rsmpi/rsmpi#194]
There is no `rustfmt.toml` file in the project, so running `cargo fmt` has no well-defined style. For example, running `cargo fmt --check` on my machine complains an awful lot...

Based on the [CI linter script](https://github.com/rsmpi/rsmpi/actions/workflows/lint.yaml), the project currently seems to rely on the default settings.

I'm not sure what the best format spec would be, but I think there should be a `rustfmt.toml` file in the project so that the formatting is consistent for everyone.

Personally, I quite like the following formatter setup, and I think it produces very clean, readable code:

```toml
use_small_heuristics = "Max"
max_width = 80
wrap_comments = true

unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
```

- [`use_small_heuristiscs = "Max"`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#use_small_heuristics): Limits long lines in certain contexts. The actual length allowed differs for different constructs, and the defaults are pretty good.
- [`max_width = 80`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#max_width): The maximum line width.
- [`wrap_comments = true`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#wrap_comments): Whether to wrap comments. Although the default is off, having consistent line widths throughout the codebase can't hurt.
- [`unstable_features = true`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#unstable_features): Enables unstable features. This is probably a more controversial option, but it allows the two options below, which greatly improve import statements. This option and below may not be necessary, but having consistent, well-structured imports can be helpful. What do you guys think?
- [`imports_granularity = "Crate"`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#imports_granularity): This ensures that all imports are grouped by module, so you don't end up with any stragglers separated from other imports.
- [`group_imports = "StdExternalCrate"`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#group_imports): Separates out standard library modules, external modules and local/crate modules to more clearly show what comes from where. 

I understand that reformatting the codebase can cause issues, so maybe the best way forward is to construct a `rustfmt.toml` file that reflects the default settings currently used. That said, I think there's an argument to be made for keeping the codebase up-to-date with the latest Rust "standards". Additionally, any PRs affected by such a change should be able to copy the format file and run `cargo fmt` on their fork of the code (I think??).

Let me know what you think. I am happy to create the necessary PR if this change is welcome. Otherwise, it's easy enough to disable autoformatting in my editor :)

**Comment by jedbrown** [comment]
I'm more fond of the `imports_granularity` and `group_imports` than with changing default styling in other cases. And with `wrap_comments` preserving lines that contain URLs, manual wrapping will often be necessary anyway (I assume everyone has a key for this). Want to make a PR with only the last three lines in your suggested configuration?

**Comment by Pencilcaseman** [comment]
Coolio. I'll create a PR in a couple minutes 👍
