### ISSUE TITLE
Build error because of different clang-sys/bindgen requirements

### ISSUE THREAD

**Issue by 5jqk2ymwqd** [rsmpi/rsmpi#44]
When I tried to build a project depending on this crate I get the following error:
> error: multiple packages link to native library `clang`, but a native library can be linked only once
> 
> package `clang-sys v0.21.2`
>     ... which is depended on by `bindgen v0.31.3`
>     ... which is depended on by `libffi-sys v0.6.0`
>     ... which is depended on by `libffi v0.6.3`
>     ... which is depended on by `mpi v0.5.2`
>     ... which is depended on by `project-using-mpi v0.1.0 (file:///path/to/project-folder)`
> links to native library `clang`
> 
> package `clang-sys v0.22.0`
>     ... which is depended on by `bindgen v0.33.2`
>     ... which is depended on by `mpi-sys v0.1.1`
>     ... which is depended on by `mpi v0.5.2`
>     ... which is depended on by `project-using-mpi v0.1.0 (file:///path/to/project-folder)`
> also links to native library `clang`

The project has only mpi as dependency (Cargo.toml):
> [dependencies]
> mpi = "*"

Maybe `mpi-sys` could depend on `bindgen v0.31.3` (libffi-sys depends [explicitly](https://github.com/tov/libffi-sys-rs/blob/master/Cargo.toml) on bindgen = "0.31.3"), too. Or do you think it is better to wait for `libffi-sys` to update to the current `bindgen`?

Thanks a bunch for this crate, I am excited to try it.

**Comment by bsteinb** [comment]
Hm, that is unfortunate, I will tie down the version of `bindgen` that `mpi-sys` uses and publish a new version to crates.io.

However, I suspect that `cargo` is being too cautious in this situation. `bindgen` and through it `clang-sys` is a build dependency of both `mpi-sys` and `libffi-sys`, so it will be linked to their `build` scripts, but not to the resulting libraries, so there will not be a mix of different versions of `clang-sys` or the native `libclang` in the resulting `mpi` library. I will open an issue for `cargo` and see what the developers think about this.

Thank you for the report and the encouraging words.

**Comment by bsteinb** [comment]
All right, I have just released `mpi-0.5.3` which should fix the issue.

**Comment by 5jqk2ymwqd** [comment]
Thank you very much.

**Comment by Eh2406** [comment]
Oddly I can not reproduce, I built a new project and added 
```
[dependencies]
mpi = "=0.5.2"
```
And ran `cargo +nightly generate-lockfile` which ran without trouble.
That error message is from the resolver that is used in `generate-lockfile`, and was added recently (by me) so this must be on a nightly. I wonder if an outdated lock file is involved?

**Comment by bsteinb** [comment]
Yes, this is on `rustc 1.26.0-nightly (c08480fce 2018-03-23)`. I can confirm that `cargo generate-lockfile` works without reporting an error. I only run into the issue I reported when I try to `cargo build`.

**Comment by Eh2406** [comment]
I was wrong. This is the older error message, not the one I just added. Sorry for the crossed wires.
