### ISSUE TITLE
Possible undefined behaviour in matched_receive_vec

### ISSUE THREAD

**Issue by adamreichold** [rsmpi/rsmpi#92]
`MatchedReceiveVec::matched_receive_vec` currently allocates and fills the receive buffer via
```rust
let mut res = Vec::with_capacity(count);
unsafe {
    res.set_len(count);
}
let status = message.matched_receive_into(&mut res[..]);
```
where `res: Vec<M>` and hence `&mut res[..]: &mut [M]`.

Even when it is assumed that the receive bytes form valid instances of `M`, i.e. ignoring #54, the uninitialized memory backing `res` could certainly contain arbitrary bit patterns which are invalid when e.g. `M == bool`. Therefore, the call to `set_len` and the creation of a mutable reference to the unformed instances of `M` is undefined behavior AFAIU.

Maybe this could be worked around by going for `res: Vec<MaybeUninit<M>>` and transmuting to `Vec<M>` only after the receive operation, but I guess this would require something along the lines of `impl<M> Equivalence for MaybeUninit<M> where M: Equivalence`?

More generally speaking and thinking about #54 again, the API could be changed so that receive operations generally handle only instances of `MaybeUninit<M>` instead of `M` so the required unsafety would be "concentrated" into calling `assume_init` in user code, at least in places where `M: FromAnyBytes` does not apply. Using `MaybeUninit<M>` could also steer user code towards avoiding the overhead of initializing memory beforing receive data into it which is required to produce a valid `&mut M` (as the API would take only `&mut MaybeUninit<M>` or even `*mut M`).

**Comment by AndrewGaspar** [comment]
Yeah, you're totally right. That's unsound. However, I think it _should_ be safe to instead just pass the uninitialized buffer directly into `MPI_Mrecv` and _then_ call `set_len`.


 At the very least, 

> `impl<M> Equivalence for MaybeUninit<M> where M: Equivalence`

I like the ideal conceptually, but I'm not sure what you're supposed to do with the, say `MaybeUninit<bool>` to validate it. Is there any safe way to validate the `bool` contained in the `MaybeUninit` before you unwrap it?

**Comment by adamreichold** [comment]
> However, I think it should be safe to instead just pass the uninitialized buffer directly into MPI_Mrecv and then call set_len.

Yes, indeed. That would just mean not be able to calling to `matched_receive_into` but reproduce its implementation here, but it is probably the least intrusive fix. (But do note that the fact that `MaybeUninit` is used would not need to become part of the API here necessarily as that trait forwarding could be hidden via a private newtype wrapper, so it could be as unintrusive even if slightly more involved at the type system level.) 

> Is there any safe way to validate the bool contained in the MaybeUninit before you unwrap it?

I don't think so. I mean you could theoretically check the bit patterns by comparing with `0_u8` and `1_u8` before calling `assume_init`, but generally this would probably be considered an assertion of a correct implementation of the participating processes.

In my personal point of view, using `MaybeUninit` and a safe API for this crate would basically mean that this crate has properly wrapped the unsafey imposed by the C API, but the received data cannot be validated at this level. So it could be considered to separate the two reasons for unsafety here: Calling into the vendor-provided C API and respecting its invariants _and_ making sure to respect types when matching sends and receives by the involved processes. Which seems nice considering that the second part would necessarily be unsafe even if the MPI implementation itself would be a completely safe Rust implementation as it is a direct consequence of pushing raw memory contents over the wire.

**Comment by adamreichold** [comment]
I think I'll try to prepare an MR investigating the use-maybeuninit-but-do-not-expose-it route...

**Comment by adamreichold** [comment]
Maybe adding
```
unsafe impl<T> FromAnyBytes for MaybeUninit<T> {}
```
in #79 would actually be all that is needed to make `MaybeUninit` work nicely with the proposed API?
